### ISSUE TITLE
Example with nested grammar?

### ISSUE THREAD

**Issue by droundy** [mrob95/Breathe#3]
I'd love to see an example with a nested grammar. I'm trying to hack up something for latex that could produce something like
```
 \frac{\sin(x^2)}{3+x}
```
from an utterance like "fraction sin x squared divided by 3 + x". I'm thinking the spec could look like "fraction <numerator> divided [by] <denominator>" but I'm not sure how to make numerator and denominator both also be math expressions. This seems like maybe a job for RuleRef, but I'm not sure how to manage that and some sort of example would be lovely.

P.S. I'm enjoying Breathe so far!

**Comment by mrob95** [comment]
Hi, glad to hear you're finding it useful!

I think the feature you're looking for is "top-level rules". It's one of the less well developed parts of Breathe but you should be able to make progress with it. Sample code for LaTeX fractions would look something like this:

```python
from breathe import Breathe, CommandContext, CommandsRef, Exec
from dragonfly import Text, AppContext

# fraction sin x squared divided by 3 + x
#  \frac{\sin(x^2)}{3+x}
Breathe.add_commands(
    AppContext(title=".tex"),
    {
        "fraction <sequence1> divided by <sequence2>": 
            Text("\\frac{") + Exec("sequence1") + Text("}{") + Exec("sequence2") + Text("}"),
    },
    [
        CommandsRef("sequence1", 8),
        CommandsRef("sequence2", 8),
    ],
    top_level=True,
)
```

I hope this is reasonably self-explanatory. `CommandsRef` creates an extra which can be an arbitrary sequence of CCR commands which are available in the current context. `Exec` executes those commands as if you had spoken them individually.

There are a couple of limitations to this system as it is implemented at the moment (RuleRef might be an improvement).
1. It increases grammar complexity quite a lot, so if you have a few of these it can cause natlink errors.
2. The nesting is only one layer deep, so in your example "sin x squared" would need to be normal commands rather than another top level.

Let me know if you have any other questions or issues. As I say this is one of the less well tested elements so there may be improvements to be made :-).

**Comment by droundy** [comment]
I'm using Kaldi, so maybe the complexity of the grammar will be less of an issue?

I'll give this a shot when I get a chance, and then if you'd like I could try to put together a pull request for a documentation addition explaining how to do this with `top_level`.

**Comment by mrob95** [comment]
Yes it may well be fine on Kaldi. Sure that would be great! Feel free to make a `docs` folder with a markdown document in if that would be a better way of structuring it than filling up the readme

**Comment by droundy** [comment]
It looks like this `top_level` solution will only work if this is the beginning of an utterance? I'm afraid that seems like a bit much to give up.  :(  I was hoping to be able to have some commands first.  I suppose I guess I just add another sequence before?

**Comment by mrob95** [comment]
Yeah just chuck in another sequence before. after might be a bit more tricky since it won't know where to break without some kind of separator word. You can also make the before sequence optional (`[<before>]`) so the command can come at the start of an utterance but doesn't have to.
