### ISSUE TITLE
Support weights for commands?

### ISSUE THREAD

**Issue by droundy** [mrob95/Breathe#5]
Is it possible to support the "weight" feature of the Kaldi backend for commands? I'm having issues with some commands being recognized when I don't want them to be.  It looks like `add_commands`  could just pass this value along.   I'm not sure how well this will work but it would be nice to be able to try it.

**Comment by mrob95** [comment]
Hmm, I'm not sure this would be easy to implement on my side. As far as I can see from the code Kaldi implements weight as a parameter on grammars and rules. For CCR commands Breathe doesn't really deal in rules, instead every command becomes an (Compound) element which is then wrapped in an Alternative and a Repetition to make a single rule.

If if it was going to be implemented in breathe the internals would probably need to be re-factored so that each call to `add_commands` creates its own rule, and then CCR is built out of RuleRefs to those. Not necessarily a huge change, though I have somewhat limited time at the moment.

@daanzu may have more thoughts or a smarter way of going about it.

**Comment by daanzu** [comment]
I think Elements should support weights. If they don't currently, it is an oversight on my part, and I would intend to fix it. I'll try to take a look. Feel free to ping me.

**Comment by mrob95** [comment]
You're right, it does look from the code like weights can be set on elements. I'll try to make a first pass at implementing something this weekend.

**Comment by daanzu** [comment]
Cool, let me know of anything.

**Comment by mrob95** [comment]
Okay @droundy #6 adds basic support for weights on command groups. Please update, test and let me know if it seems to be working as I only have kaldi set up on work VMs at the moment 🙃
